version: '3'

services:

    app:
        image: laravel_app
        build:
            context: .
            dockerfile: docker/dev/Dockerfile
        container_name: laravel_app
        restart: unless-stopped
        ports:
            - '80:80'
        volumes:
            - ./:/var/www
