services:

    redis:
      image: redis:4.0
      container_name: laravel_redis
      ports:
        - "6379:6379"
      networks:
        - app-network

    db:
      image: postgres:15
      restart: always
      container_name: laravel_db
      environment:
        POSTGRES_DB: ${DB_DATABASE}
        POSTGRES_USER: ${DB_USERNAME}
        POSTGRES_PASSWORD: ${DB_PASSWORD}
      ports:
        - ${PORT_DB:-5432}:5432
      volumes:
        - db_volume:/var/lib/postgresql/data
      networks:
        - app-network

    mongodb:
      container_name: mongodb
      image: mongo:8
      ports:
        - ${PORT_MONGO_DB:-27017}:27017
      environment:
        - MONGO_INITDB_ROOT_USERNAME=root
        - MONGO_INITDB_ROOT_PASSWORD=1234
        - MONGO_INITDB_DATABASE=admin
      volumes:
        - mongo-database:/data/db
      networks:
        - app-network

volumes:
  db_volume:
  mongo-database:

networks:
  app-network:
    driver: bridge
